#!/bin/sh
set -e

case "$1" in
    remove|purge)
        if [ -d /run/systemd/system ]; then
            systemctl disable comfy-archive-agent.service || true
            systemctl daemon-reload || true
        fi
        ;;
esac

exit 0
