#!/bin/sh
set -e

case "$1" in
    remove|deconfigure|upgrade)
        if [ -d /run/systemd/system ]; then
            systemctl stop comfy-archive-agent.service || true
        fi
        ;;
esac

exit 0
